eureka: 
  client: 
    registerWithEureka: true 
    fetchRegistry: true 
    service-url: 
      defaultZone: http://localhost:8761/eureka/ 
  instance: 
    hostname: localhost 
server: 
  port: 8000 
spring: 
  application: 
      name: API-GATE-WAY 
  cloud: 
    gateway: 
      routes: 
      - id: BANK-API 
        uri: 
          lb://BANK-API 
        predicates: 
        - Path=//bank/** 
      - id: SBI-BANK-API 
        uri: 
          lb://SBI-BANK-API 
        predicates: 
        - Path=//sbi/**